name : Coding Stats Gist Updater
on:
  push:
    branches:
      - master

jobs:
  coding_stats:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v1
        with:
          go-version: '^1.13.1'
        env: 
          GIST_TOKEN: ${{ secrets.GIST_TOKEN }}
          GIST_ID: ${{ secrets.GIST_ID }}
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          WAKATIME_EMBED_URL: ${{ secrets.WAKATIME_EMBED_URL }}
      - run: go run main.go
                                  
