name: Update gist with Todoist items
on:
  push:
  schedule:
    - cron: '0 */3 * * *' # Every three hours
jobs:
  update-gist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          ref: master
      - name: Update gist
        uses: incrypt0/WeeklyCodingStats@master
        env:
          GIST_TOKEN: ${{ secrets.GH_TOKEN }}
          GIST_ID: ${{ secrets.GIST_ID }}
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          WAKATIME_EMBED_URL:${{ secrets.WAKATIME_EMBED_URL}}
