name : Update Coding Stats
on:
  push: 
  schedule:
    - cron: "25 11 * * *"

jobs:
  coding_stats:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2.0.3
        with:
          go-version: '1.14.2'
          
      - name: run task
        run: |
          echo $GIST_TOKEN
          go run main.go -api
          echo $GIST_TOKEN
        env: 
          GIST_TOKEN: ${{ secrets.GIST_TOKEN }}
          GIST_ID: ${{ secrets.GIST_ID }}
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          WAKATIME_EMBED_URL: ${{ secrets.WAKATIME_EMBED_URL }} 
       
                                  
